### ISSUE TITLE
Change icd endpoint to icds

### ISSUE THREAD

**Issue by ka1to1** [MarcusDunn/leftindust-backend#10]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Change the query `icd` to take in an array of icdCodes instead of one, and rename it to `icds`

**Comment by ka1to1** [comment]
#21 This is an API inconsistency

**Comment by MarcusDunn** [comment]
fixed in https://github.com/MarcusDunn/leftindust-backend/commit/7b7c0092ca6b413e2f4ed48bad7a6330248970f2
