### ISSUE TITLE
Unify float and Integer in datatypes

### ISSUE THREAD

**Issue by ka1to1** [MarcusDunn/leftindust-backend#12]
**Is your feature request related to a problem? Please describe.**
Yes. The `float` type is redundant as in JS land float, int, long, short === number, so this explicit specification seems unnecessary to me, and may pose redundancy issues later down the road.

**Describe the solution you'd like**
Unify the types to create a new type called number

**Comment by MarcusDunn** [comment]
closing for now, we discussed on discord. feel free to reopen later
