### ISSUE TITLE
Rename all form related endpoints to survey

### ISSUE THREAD

**Issue by ka1to1** [MarcusDunn/leftindust-backend#14]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
`addFormTemplate` -> `addSurveyTemplate`
`submitForm` -> `submitSurvey`
`forms` -> `surveys`

**Comment by MarcusDunn** [comment]
fixed https://github.com/MarcusDunn/leftindust-backend/commit/53cb2dbfc1aa5ba20af95c401c55a6cf25550aff
