### ISSUE TITLE
ICD search always returns 1 result 

### ISSUE THREAD

**Issue by ka1to1** [MarcusDunn/leftindust-backend#9]
**Describe the bug**
ICD search always returns 1 result when there should be more

**To Reproduce**
Search for any keyword that is expected to have more than one result

**Expected behavior**
I should get more results

**Comment by MarcusDunn** [comment]
fixed in https://github.com/MarcusDunn/leftindust-backend/commit/f8d457e125daf8a0504d43f09e0073eba884198d
